FROM apache/nifi:latest

# Expor as portas do NiFi
EXPOSE 8080 8443

# Definir as variáveis de ambiente (se necessário)
ENV NIFI_WEB_HTTP_PORT=8080

# Comando para iniciar o NiFi
CMD ["bin/nifi.sh", "run"]
