FROM apache/nifi:latest

# Listar arquivos no diretório 'bin'
RUN ls -l /opt/nifi/nifi-current/bin

# Expor as portas do NiFi
EXPOSE 8080 8443

# Iniciar o NiFi
CMD ["/opt/nifi/nifi-current/bin/nifi.sh", "run"]
